name: xai_course
channels:
  - pytorch
  - defaults
dependencies:
  - altair=4.1.0
  - pip=22.3.1
  - pytorch=1.13.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.64.1
  - pip:
    - lime==0.2.0.1
    - numpy==1.23.5
    - opencv-python==4.6.0.66
    - pytorch-lightning==1.8.5.post0
    - tensorflow==2.11.0
    - ttach==0.0.3
