name: XAI
channels:
  - pytorch
  - jamespreed
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - addict=2.4.0
  - albumentations=1.3.1
  - altair=5.2.0
  - ansi2html=1.9.1
  - anyio=4.2.0
  - aom=3.5.0
  - appnope=0.1.3
  - archspec=0.2.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.2
  - bitarray=2.9.2
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.7.0
  - blosc=1.21.3
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2023.12.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - catboost=1.2.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - conda=23.11.0
  - conda-libmamba-solver=23.12.0
  - conda-minify=0.1.2
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dash=2.14.2
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - dash_cytoscape=0.2.0
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - deap=1.4.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - distro=1.8.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=5.1.2
  - filelock=3.13.1
  - flask=3.0.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.10.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - gevent=23.9.0.post1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - graphite2=1.3.13
  - graphviz=8.0.5
  - greenlet=3.0.3
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.6
  - imagecodecs=2021.8.26
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - interpret=0.5.0
  - interpret-core=0.5.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jasper=2.0.33
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.12.2
  - jupyter_server_terminals=0.5.1
  - jupyterlab=4.0.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.1.2
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libebm=0.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.25
  - libopencv=4.7.0
  - libopus=1.3
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - librsvg=2.56.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuv=1.46.0
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=2.0.3
  - libxml2=2.10.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightgbm=4.2.0
  - lime=0.2.0.1
  - llvm-openmp=17.0.6
  - llvmlite=0.41.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - menuinst=2.0.1
  - mistune=3.0.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.14.0
  - nbconvert-core=7.14.0
  - nbconvert-pandoc=7.14.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.9.1
  - networkx=3.2.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.3.0
  - openssl=3.2.0
  - overrides=7.4.0
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=2.1.4
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - partd=1.4.1
  - pathos=0.3.1
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.2
  - pixman=0.43.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.18.0
  - pluggy=1.0.0
  - pox=0.3.3
  - ppft=1.7.6.7
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - py-xgboost=2.0.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyobjc-core=9.0
  - pyobjc-framework-cocoa=9.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python_abi=3.11
  - pytorch=2.1.2
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - qudida=0.0.4
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.32.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.21
  - salib=1.4.7
  - scikit-image=0.20.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.1
  - seaborn-base=0.13.1
  - send2trash=1.8.2
  - setuptools=69.0.3
  - shap=0.42.1
  - six=1.16.0
  - slicer=0.0.7
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - svt-av1=1.4.1
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.3
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.0
  - torchvision=0.16.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - truststore=0.8.0
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023d
  - uri-template=1.3.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - x264=1!152.20180806
  - xgboost=2.0.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zfp=0.5.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope.event=5.0
  - zope.interface=6.1
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - aix360==0.3.0
      - anchor-exp==0.0.2.0
      - annotated-types==0.6.0
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - cymem==2.0.8
      - langcodes==3.3.0
      - murmurhash==1.0.10
      - preshed==3.0.9
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - smart-open==6.4.0
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.2
      - typer==0.9.0
      - wasabi==1.1.2
      - weasel==0.3.4
